import { db } from "@/lib/db";


// create a new invite (includes coach select) 
// token is auto-generated by Prisma
export async function createInvite(coachId: string, expiresAt: Date) {
  return db.inviteLink.create({
    data: { coachId, expiresAt },
    select: { id: true, token: true, coachId: true, expiresAt: true, usedById: true, createdAt: true },
  });
}

export async function findInviteByToken(token: string) {
  return db.inviteLink.findUnique({
    where: { token },
    select: {
      id: true,
      token: true,
      coachId: true,
      expiresAt: true,
      usedById: true,
      createdAt: true,
      coach: { select: { id: true, name: true } },
    },
  });
}

export async function markInviteUsed(token: string, athleteId: string) {
  return db.inviteLink.update({
    where: { token },
    data: { usedById: athleteId },
  });
}
