// Prisma queries for invite links.
// Token generation and TTL calculation are handled by the service layer.
import { db } from "@/lib/db";

// token is a cuid() generated by Prisma's @default — no need to pass it explicitly.
export async function createInvite(coachId: string, expiresAt: Date) {
  return db.inviteLink.create({
    data: { coachId, expiresAt },
    select: { id: true, token: true, coachId: true, expiresAt: true, usedById: true, createdAt: true },
  });
}

export async function findInviteByToken(token: string) {
  return db.inviteLink.findUnique({
    where: { token },
    select: {
      id: true,
      token: true,
      coachId: true,
      expiresAt: true,
      usedById: true,
      createdAt: true,
      coach: { select: { id: true, name: true } },
    },
  });
}

// Records which athlete accepted the invite. usedById being set is the replay-attack guard
// checked in the service before creating the coach-athlete relation.
export async function markInviteUsed(token: string, athleteId: string) {
  return db.inviteLink.update({
    where: { token },
    data: { usedById: athleteId },
  });
}
