/**
 * POST /api/viz/reports
 *
 * Body: { type: "weekly", athleteId?: string, weekStart?: string }
 *
 * Returns a binary PDF generated by the Python viz service.
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { VIZ_AVAILABLE, getWeeklyReport } from "@/lib/viz";

type SessionUser = { id?: string; role?: string };

async function fetchSessionsForReport(userId: string, role: string, athleteId?: string) {
  const targetId = role === "COACH" && athleteId ? athleteId : userId;

  return db.session.findMany({
    where: { athleteId: targetId },
    orderBy: { date: "asc" },
    include: {
      types: true,
      sets: { include: { laps: true } },
      feedback: { include: { incidents: true } },
    },
  });
}

function shapeSessions(sessions: Awaited<ReturnType<typeof fetchSessionsForReport>>) {
  return sessions.map((s) => ({
    id: s.id,
    date: s.date.toISOString().slice(0, 10),
    title: s.title,
    durationMin: s.durationMin,
    types: s.types.map((t) => t.type),
    sets: s.sets.map((st) => ({
      order: st.order,
      abandoned: st.abandoned,
      laps: st.laps.map((l) => ({
        distance: l.distance,
        timeSeconds: l.timeSeconds,
      })),
    })),
    feedback: s.feedback
      ? {
          rpe: s.feedback.rpe,
          fatigue: s.feedback.fatigue,
          note: s.feedback.note,
        }
      : null,
    incidents: s.feedback?.incidents.map((i) => ({
      type: i.type,
      bodyPart: i.bodyPart,
      severity: i.severity,
    })) ?? [],
  }));
}

async function fetchAthleteInfo(athleteId: string) {
  return db.user.findUnique({
    where: { id: athleteId },
    select: { id: true, name: true },
  });
}

async function fetchCoachInfo(userId: string, role: string, athleteId?: string) {
  if (role === "COACH") {
    return db.user.findUnique({ where: { id: userId }, select: { id: true, name: true } });
  }
  // athlete: find their coach
  const relation = await db.coachAthleteRelation.findFirst({
    where: { athleteId: userId },
    include: { coach: { select: { id: true, name: true } } },
  });
  return relation?.coach ?? null;
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  const session = await auth();
  const user = session?.user as SessionUser | undefined;

  if (!user?.id || !user.role) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const type = body.type as string | undefined;
  if (type !== "weekly") {
    return NextResponse.json({ error: "Unsupported report type" }, { status: 400 });
  }

  if (!VIZ_AVAILABLE) {
    return NextResponse.json({ unavailable: true, error: "PDF reports require the analytics service, which is not configured in this environment" }, { status: 503 });
  }

  const athleteId = typeof body.athleteId === "string" ? body.athleteId : undefined;
  const targetAthleteId =
    user.role === "COACH" && athleteId ? athleteId : user.role === "ATHLETE" ? user.id : undefined;

  if (!targetAthleteId) {
    return NextResponse.json({ error: "No athlete target" }, { status: 400 });
  }

  const weekStart =
    typeof body.weekStart === "string"
      ? body.weekStart
      : (() => {
          const d = new Date();
          d.setDate(d.getDate() - d.getDay() + 1);
          return d.toISOString().slice(0, 10);
        })();

  try {
    const [rawSessions, athleteInfo, coachInfo] = await Promise.all([
      fetchSessionsForReport(user.id, user.role, athleteId),
      fetchAthleteInfo(targetAthleteId),
      fetchCoachInfo(user.id, user.role, athleteId),
    ]);

    const sessions = shapeSessions(rawSessions);

    // Filter to sessions within the target week
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    const weekEndStr = weekEnd.toISOString().slice(0, 10);
    const weekSessions = sessions.filter((s) => s.date >= weekStart && s.date <= weekEndStr);

    const pdfBuffer = await getWeeklyReport({
      athlete_name: athleteInfo?.name ?? "Athlete",
      coach_name: coachInfo?.name ?? "Coach",
      week_start: weekStart,
      sessions: weekSessions,
    });

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="weekly-report-${weekStart}.pdf"`,
      },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Internal server error";
    console.error("[viz/reports]", msg);
    return NextResponse.json({ error: msg }, { status: 502 });
  }
}
